Algoritmo "tetese"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/12/2022
Var
// Seção de Declarações das variáveis 
          xczx

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

         cxxz
Fimalgoritmo