Algoritmo "ContadorComRepita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : GAUANABARA
// Descrição   : EXEMPLO DE USO DO REPITA (DO)
// Autor(a)    : ROGERIO
// Data atual  : 09/12/2022
Var
// Seção de Declarações das variáveis 
Cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Cont <- 1
Repita
Escreva(Cont)
Cont <- Cont +1
Ate (Cont > 10)
Fimalgoritmo