Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/10/2022
Var
// Seção de Declarações das variáveis 
Nome: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreva("Saudações, por favor digite o seu nome: ")
Leia(Nome)
Escreva("Saudações, meu nome é ", Nome)



Fimalgoritmo