Algoritmo "Primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/10/2022
Var
// Seção de Declarações das variáveis 
Msg: caractere
Msg2: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc..].
Msg <- "Olá Mundo"
Msg2 <- "Escapei da maldição!"
Escreval(Msg)
Escreva(Msg2)

Fimalgoritmo

