Algoritmo "TesteLogico"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/11/2022
Var
// Seção de Declarações das variáveis
A, B, C : Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
A <- 2
B <- 3
C <- 5
Escreva((A=B) ou nao(C>A))

Fimalgoritmo